# Alarm for WAF blocked requests
resource "aws_cloudwatch_metric_alarm" "waf_blocked_requests" {
  alarm_name        = "waf-lab-blocked-requests"
  alarm_description = "WAF blocked more than 10 requests in 5 minutes"

  namespace   = "AWS/WAFV2"
  metric_name = "BlockedRequests"

  dimensions = {
    WebACL = aws_wafv2_web_acl.alb_waf.name
    Rule   = "ALL"
    Region = "us-east-1"
  }

  statistic           = "Sum"
  period              = 300 # 5 minutes
  evaluation_periods  = 1   # Evaluate over 1 period
  threshold           = 5   # Trigger alarm if 5 or more blocked requests occur in 5 minutes
  comparison_operator = "GreaterThanThreshold"

  alarm_actions = [
    aws_sns_topic.waf_alerts.arn
  ]

  tags = merge(local.common_tags, {
    Name = "waf-lab-blocked-requests-alarm"
  })
}

## Alarm for ALB 5xx errors  generated by ALB
resource "aws_cloudwatch_metric_alarm" "alb_5xx" {
  alarm_name        = "waf-lab-alb-5xx"
  alarm_description = "Alarm when ALB returns 5xx errors"

  namespace   = "AWS/ApplicationELB"
  metric_name = "HTTPCode_ELB_5XX_Count"

  dimensions = {
    LoadBalancer = aws_lb.application.arn_suffix
  }

  statistic           = "Sum"
  period              = 300 # 5 minutes
  evaluation_periods  = 1   # Evaluate over 1 period
  threshold           = 5   # Trigger alarm if 5 or more 5xx errors occur in 5 minutes
  comparison_operator = "GreaterThanOrEqualToThreshold"

  alarm_actions = [
    aws_sns_topic.waf_alerts.arn
  ]

  tags = merge(local.common_tags, {
    Name = "waf-lab-alb-5xx-alarm"
  })
}

# Alarm for 5xx errors returned by EC2/Apache
resource "aws_cloudwatch_metric_alarm" "target_5xx" {
  alarm_name        = "waf-lab-target-5xx"
  alarm_description = "Alarm when backend targets return 5xx errors"

  namespace   = "AWS/ApplicationELB"
  metric_name = "HTTPCode_Target_5XX_Count"

  dimensions = {
    LoadBalancer = aws_lb.application.arn_suffix
    TargetGroup  = aws_lb_target_group.apache.arn_suffix
  }

  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = 5
  comparison_operator = "GreaterThanOrEqualToThreshold"

  alarm_actions = [
    aws_sns_topic.waf_alerts.arn
  ]

  tags = merge(local.common_tags, {
    Name = "waf-lab-target-5xx-alarm"
  })
}

# Alarm for unhealthy targets in the target group
resource "aws_cloudwatch_metric_alarm" "unhealthy_targets" {
  alarm_name        = "waf-lab-unhealthy-targets"
  alarm_description = "Alarm when one or more ALB targets become unhealthy"

  namespace   = "AWS/ApplicationELB"
  metric_name = "UnHealthyHostCount"

  dimensions = {
    LoadBalancer = aws_lb.application.arn_suffix
    TargetGroup  = aws_lb_target_group.apache.arn_suffix
  }

  statistic           = "Maximum"
  period              = 60
  evaluation_periods  = 2
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"

  alarm_actions = [
    aws_sns_topic.waf_alerts.arn
  ]

  tags = merge(local.common_tags, {
    Name = "waf-lab-unhealthy-targets-alarm"
  })
}
